apiVersion: apps/v1
kind: Deployment
metadata:
  name: formservice
spec:
  selector:
    matchLabels:
      name: formservice
  template:
    metadata:
      labels:
        name: formservice
    spec:
      containers:
        - name: app
          image: 306881650362.dkr.ecr.us-gov-west-1.amazonaws.com/faas-sandb/microservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: formservice
# #   namespace: default
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       name: formservice
# #   template:
# #     metadata:
# #       labels:
# #         name: formservice
# #     spec:
# #       affinity:
# #         podAntiAffinity:
# #           preferredDuringSchedulingIgnoredDuringExecution:
# #             - podAffinityTerm:
# #                 labelSelector:
# #                   matchExpressions:
# #                     - key: app
# #                       operator: In
# #                       values:
# #                         - formservice
# #                 topologyKey: kubernetes.io/hostname
# #               weight: 100
# #       containers:
# #         - name: formservice-app
# #           image: 306881650362.dkr.ecr.us-gov-west-1.amazonaws.com/faas-sandb/microservice:latest
# #           env:
# #             - name: SPRING_PROFILES_ACTIVE
# #               value: dev
# #             # - name: SPRING_DATASOURCE_URL
# #             #   value: jdbc:postgresql://formservice-postgresql.default.svc.cluster.local:5432/formservice
# #             # - name: SPRING_DATASOURCE_USERNAME
# #             #   value: formservice
# #             # - name: SPRING_DATASOURCE_PASSWORD
# #             #   valueFrom:
# #             #     secretKeyRef:
# #             #       name: formservice-postgresql
# #             #       key: postgresql-password
# #             - name: JAVA_OPTS
# #               value: ' -Xmx256m -Xms256m'
# #           resources:
# #             requests:
# #               memory: '512Mi'
# #               cpu: '500m'
# #             limits:
# #               memory: '1Gi'
# #               cpu: '1'
# #           ports:
# #             - name: http
# #               containerPort: 8181
# #           readinessProbe:
# #             httpGet:
# #               path: /management/health
# #               port: http
# #             initialDelaySeconds: 20
# #             periodSeconds: 15
# #             failureThreshold: 6
# #           livenessProbe:
# #             httpGet:
# #               path: /management/health
# #               port: http
# #             initialDelaySeconds: 120
